#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Title: **1º Create the Server (Only do this the first time)**
# Kernel: Python 3
# Cells: 2 code, 5 markdown

# ────────────────────────────────────────────────────────────────────────
# 
# ```
# ███╗   ███╗██╗███╗   ██╗███████╗ ██████╗ ██████╗ ██╗      █████╗ ██████╗
# ████╗ ████║██║████╗  ██║██╔════╝██╔════╝██╔═══██╗██║     ██╔══██╗██╔══██╗
# ██╔████╔██║██║██╔██╗ ██║█████╗  ██║     ██║   ██║██║     ███████║██████╔╝
# ██║╚██╔╝██║██║██║╚██╗██║██╔══╝  ██║     ██║   ██║██║     ██╔══██║██╔══██╗
# ██║ ╚═╝ ██║██║██║ ╚████║███████╗╚██████╗╚██████╔╝███████╗██║  ██║██████╔╝
# ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝
# ```
# Create a Minecraft Server on Google Colab!
# 
# The script below will initiate your server. First, you will need to create the server to be able to use it - don't worry, the scripts below will do the majority of the work for you. Perhaps you want to change the server's region, check below.
# 
# Original: https://github.com/thecoder-001/MineColab

# ────────────────────────────────────────────────────────────────────────
# # **1º Create the Server (Only do this the first time)**
# 
# The code below will create your server and accept the EULA. When you use these scripts, your server will be ready to start.

# ────────────────────────────────────────────────────────────────────────
# 
# **Download the Minecraft Server**
# 
# The code below will download Paper, a type of high-performance Vanilla server that allows the use of plugins. If you want to use another type of server.jar, put it in the Drive folder manually.
# 
# The server files will be saved on your Google Drive (in the Google account you choose or are using).

# ────────────────────────────────────────────────────────────────────────
# %%  [4]

# Change "1.20.1" to the desired version.
# Available tested versions:
# - 1.20.2
# - 1.20.1
# - 1.20
# - 1.19.4
# - 1.19.3
# - 1.19.2
# - 1.19.1
# - 1.19
# - 1.18.2
# - 1.18.1
# - 1.18
# - 1.17.1
# - 1.17
# - 1.16.5
# - 1.16.4
# - 1.16.3
# - 1.15.2
# - 1.14.4
# - 1.13.2
# - 1.12.2
# - 1.11.2
# - 1.10.2
# - 1.9.4
# - 1.8.8
# Newer versions might work too, however this isn't guaranteed.

version = '1.20.2'

# Choose server type. Currently available versions:
# - paper (Most vanilla. It's the same as SPIGOT, bukkit, etc.)
# - forge (For using MODS. It's basically FORGE) [Note, installation takes approximately 10-15 minutes, wait for "COMPLETED" after executing the first step.]
# - fabric (For playing Fabric. It's an alternative to Forge)

server_type = 'paper'

# Print experimental build warning -- no longer needed
# if version == '1.18' and server_type == 'paper':
#  print("<!> Paper 1.18 builds are still experimental. Make regular Backups!")

from google.colab import drive
import requests
import json

drive.mount('/content/drive')

# Create the directory which will be used for the server
! mkdir "/content/drive/My Drive/Minecraft-server"
%cd "/content/drive/My Drive/Minecraft-server"

# Internal init...

a = requests.get("https://papermc.io/api/v2/projects/paper/versions/" + version)
#print(a.json()["builds"][-1])
b = requests.get("https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]))
#print(b.json()["downloads"]["application"]["name"])
print("https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]) + "/downloads/" + b.json()["downloads"]["application"]["name"])

paperURL = "https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]) + "/downloads/" + b.json()["downloads"]["application"]["name"]

forgeURL = "https://serverjars.com/api/fetchJar/modded/forge/" + version

jar_name = {'paper': 'server.jar', 'fabric': 'fabric-installer.jar', 'forge': 'forge-installer.jar'}
url = {
    'paper': (paperURL),
    'fabric': 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar',
    'forge': (forgeURL)
    }

print('Downloading to Google Drive...')

r = requests.get(url[server_type])

if r.status_code == 200:
  with open('/content/drive/My Drive/Minecraft-server/' + jar_name[server_type], 'wb') as f:
    f.write(r.content)
else:
  print('Error '+ str(r.status_code) + '! Most likely you entered an unsupported version. Try running the code again if you think that shouldn\'t have happened.')

# Running specific install path.
if server_type == 'fabric':
  !java -jar fabric-installer.jar server -mcversion $version -downloadMinecraft

if server_type == 'forge':
  %cd "/content/drive/My Drive/Minecraft-server"
  !java -jar forge-installer.jar --installServer

# Saving config
colabconfig = {"server_type": server_type,
               "server_version": version}
json.dump(colabconfig, open("colabconfig.json",'w'))

print('Completed!')  # todo: Would show even after erroring.

# Please read the file stored in your server folder before running this command.
# Also, go to https://www.minecraft.net/en-us/eula to read Minecraft's EULA.

# Make sure Drive is mounted
from google.colab import drive
drive.mount('/content/drive')

%cd "/content/drive/My Drive/Minecraft-server"
!echo "eula=true" >> eula.txt


# ────────────────────────────────────────────────────────────────────────
# # **-> Start the Minecraft server - Use this whenever you want to open it.**
# 
# You can change the REGION in the code below; this is important for LAG and PING. Use regions closest to you. The default region is the United States, which is not recommended for countries in South America or Spain. For these, you can use regions like 'sa' (Brazil) and 'eu' (Europe). You can change it in the code below where indicated.
# 
# **IMPORTANT:**
# 
# The IP will change every time you restart the server.
# You need to enter your Ngrok TOKEN below. Visit https://dashboard.ngrok.com/auth to obtain your token (you need to have an account created on Ngrok).
# To enter a command through the console, you can do it here. Basically, the section below will be your console (where you will enter commands and see logs).
# It is advisable to keep the Google Colab tab open so that the server does not close. It may ask you to solve a captcha from time to time.

# ────────────────────────────────────────────────────────────────────────
# %%  [6]

import os
import re
import json
import glob

# Update the package lists
!sudo apt update &>/dev/null && echo "apt cache successfully updated" || echo "apt cache update failed, you might receive stale packages"

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Change directory to the Minecraft server folder on Google Drive
%cd "/content/drive/My Drive/Minecraft-server"
!ls #list the directory contents (to verify that working directory was changed)

# Import config file.
if os.path.isfile("colabconfig.json"):
  colabconfig = json.load(open("colabconfig.json"))
else:
  colabconfig = {"server_type": "generic"} # using default, if config doesn't exist.
  json.dump(colabconfig, open("colabconfig.json",'w'))

# Install OpenJDK 17
# !wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
# !sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ &>/dev/null || echo "Failed to add repo. Still can be ignored if openjdk17 gets installed."
if colabconfig["server_type"] == "forge":
   version = colabconfig["server_version"]
   if colabconfig["server_version"] < "1.17":
    !sudo apt-get install openjdk-15-jre-headless &>/dev/null && echo "Yay! Openjdk15 has been successfully installed." || echo "Failed to install OpenJdk15."
   else:
    !sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "Yay! Openjdk17 has been successfully installed." || echo "Failed to install OpenJdk17."
else:
  !sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "Yay! Openjdk17 has been successfully installed." || echo "Failed to install OpenJdk17."

#Perform java version check
java_ver = !java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==1{print $2}'
if java_ver[0] == "17" :
  print("Openjdk17 is working correctly, you are good to go.")
else:
  print("Openjdk17 doesn't seem to be installed or isn't working, falling back to java", java_ver[0], ". You might experience reduced performance. Minecraft 1.17 and above might fail to launch.")

# Server jar names.
jar_list = {'paper': 'server.jar', 'fabric': 'fabric-server-launch.jar', 'generic': 'server.jar', 'forge': 'forge.jar'}
jar_name = jar_list[colabconfig["server_type"]]

# Java arguments.
if colabconfig["server_type"] == "paper":
  server_flags = "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
else:
  server_flags = "" # aiker's flags might negatively impact performance on non-paper servers.
memory_allocation = "-Xms8704M -Xmx8704M"

# Choose the tunnel service you want to use
# Available options: ngrok, argo, playit
tunnel_service = "playit"
print("Using", tunnel_service)

!java $memory_allocation $server_flags -jar $jar_name nogui



# ────────────────────────────────────────────────────────────────────────
# **FAQ - THINGS YOU NEED TO KNOW**
# 
# Google Colab is not intended for creating Minecraft servers, but it can be done. Google Colab promises to work continuously for 12 hours; however, it may close if there is no one actively reviewing the page or using the console. In essence, if the page detects inactivity, the process will terminate. The performance is approximately 12 GB of RAM, along with a processor with a speed of 2.2 GHz and 2 threads. This is better than many paid hosting services, but it lacks support and does not guarantee to be open all the time. Mods can be installed, but it is not advisable to overload it with too many, just like plugins. The primary limitation of this server is its processor, which is not very powerful. Any hosting for $12 can offer a server of higher quality. If you plan to create something for many users, using a dedicated hosting service is much better. The servers used are from Google along with the Ngrok proxy.
